version: "3"
services:

  db:
    image: mariadb
    container_name: webmonitor_mysql
    hostname: mysql
    restart: always
    ports:
      - 3333:3306
    volumes:
      - D:\code/power_monitor\db:/var/lib/mysql

    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=webmonitor
      - MYSQL_USER=webmonitor_user
      - MYSQL_PASSWORD=webmonitor_pass
      - MYSQL_ROOT_PASSWORD=webmonitor_pass

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - D:\code/power_monitor\src/.:/code
    ports:
      - "4000:8000"
    depends_on:
         - db