version: "3"
services:

  db:
    image: ${DB_IMAGE}
    container_name: webmonitor_mysql
    hostname: mysql
    restart: always
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_VOLUMES}:/var/lib/mysql

    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=webmonitor
      - MYSQL_USER=webmonitor_user
      - MYSQL_PASSWORD=webmonitor_pass
      - MYSQL_ROOT_PASSWORD=webmonitor_pass

  web:
    build: .
    env_file:
      - .env
    command: sh -c "service cron start && 
                    echo ${TESTTEST} &&
                    python /code/manage.py makemigrations &&
                    python /code/manage.py migrate && 
                    python manage.py runserver 0.0.0.0:8000"
      

    volumes:
      - ${CODE_VOLUMES}.:/code
    ports:
      - "4000:8000"
    depends_on:
         - db